version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dna_test_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Aa@123456
      - MSSQL_PID=Developer
    ports:
      - "1435:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - dna_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: dna_test_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver:1433;databaseName=dna_test_db;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=Aa@123456
    depends_on:
      - sqlserver
    networks:
      - dna_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dna_test_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - dna_network

volumes:
  sqlserver_data:

networks:
  dna_network:
    driver: bridge 