version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dna_test_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Aa@123456
      - MSSQL_PID=Developer
    ports:
      - "1435:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - dna_network

volumes:
  sqlserver_data:

networks:
  dna_network:
    driver: bridge 